webtalk_init -webtalk_dir C:/Users/ASUS/Documents/GitHub/mobilenetv2_nexys_a7_vivado/baseline/baseline.sim/sim_1/behav/xsim/xsim.dir/tb_mnv2_71layer_smoke_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Oct  5 16:32:00 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "935d7b3e-0aae-4ec4-8fbe-9983335087b7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "aefd344a7ecd47c5b9c2656d2f4597a4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-12500H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3110 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10845 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "253.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "2506856_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1109808356 -regid "" -xml C:/Users/ASUS/Documents/GitHub/mobilenetv2_nexys_a7_vivado/baseline/baseline.sim/sim_1/behav/xsim/xsim.dir/tb_mnv2_71layer_smoke_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/ASUS/Documents/GitHub/mobilenetv2_nexys_a7_vivado/baseline/baseline.sim/sim_1/behav/xsim/xsim.dir/tb_mnv2_71layer_smoke_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/ASUS/Documents/GitHub/mobilenetv2_nexys_a7_vivado/baseline/baseline.sim/sim_1/behav/xsim/xsim.dir/tb_mnv2_71layer_smoke_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
